apiVersion: v1
kind: Service
metadata: 
  name: audiobookshelf
spec: 
    ports:
      - port: 3005
        targetPort:  # Assuming your container listens on port 80
    selector: 
        app: audiobookshelf
    type: ClusterIP 
